<?php
/*This PHP attends to the conjunctions  of practical reasoning scheme, the other conjunctions (argumentation schemes for consultations are created as part
 * of the consultation construction tool (page no. 8).
*
* in this PHP the following conjunctions could be created and deleted:
* 1) Proposition Conjunctions.
* 2) Values Conjunctions
*
* These conjunctions are created in two parts:
* 1) an array of conjuncts is firstly created - the members of the array are displayed on the right hand side of each forum
* 2) the array is then submitted to the database when the user is happy with it, this involves: creating new entry in the conjunction table to bind the elements of the array together
* then each element is added to the adequate _occurrence table*/

/*note that the admin tool allows the user to add and delete relations from the database, but it has no edit function.*/
/*all the html is printed via php print commands*/

/*
AZW - changed on Nov 12.  Was getting an error:

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /Users/azwyner/Sites/soct7.1/admin/admin_header.php:8) in /Users/azwyner/Sites/soct7.1/admin/conj.php on line 19
The order of these lines is different from prim.php and intr.php. I've made it just like them. 
Do not otherwise see the point of the differences.  admin_header.php is used in some
pages for colours, which are sometimes nice...but the colours do not
appear everywhere consistently.  This is a style issue.
Not sure I see any problem with just deleting the admin_header....have to ask and experiment.
Seems OK.
include('../support/database_connect_admin.php');
include ('admin_header.php');
include('admin_utility.php');
session_start();
*/

session_start();
include('../support/database_connect_admin.php');
include('admin_utility.php');

?>


<?php 
/*if the mode is not set --> set to undefined to avoid error message*/
if (!isset($_POST['mode'])) {
	$_POST['mode'] = "undefine";
}

/*The actual entry to the database - depends on the forum submitted.
 * Ids are auto generated by the sql (auto incremented fields) */
	switch($_POST['mode']){
		
		case "insert-proposition-conjunction":		
			if(isset($_SESSION['conjPorporties'])){
				//inserts
				InsertNewConjunction("prop_occurrence", "proposition", "proposition_string", $_SESSION['conjPorporties']);				
			}
		break;
		
		case "reset-proposition-conjunction":
			unset ($_SESSION['conjPorporties']);
			break;
			
		case "form-proposition-conjunction":
			//adds a new proposition to the list of propositions to be added to the DB as a conjunction of propositions
			if(isset($_SESSION['conjPorporties']) && $_POST['proposition']!="N/A"){
				$ConjProps = $_SESSION['conjPorporties'];
				array_push($ConjProps, $_POST['proposition']);
				$_SESSION['conjPorporties'] = $ConjProps;
			}
			break;

			
	//VALUES
			case "insert-value-conjunction":
				/*here it is different because for every value_occurrence we insert a row to value_occurrence_default_choice 
				 * with the default choice of this value*/
				if(isset($_SESSION['conjValues'])){
					InsertNewConjunction("value_occurrence", "value", "value_name", $_SESSION['conjValues']);
					$ConjValue = $_SESSION['conjValues'];
					$conjunctionIDV = GenerateConjunctionID();
					
					foreach ($ConjValue as $valueOccurrence){
						$valueName = $valueOccurrence[0];
						$defaultChoice = $valueOccurrence[1];
						$valueIDQuery = mysqli_query("select value_id from value where value_name='$valueName'") or trigger_error(mysqli_error());
						//GetNewID
						while($infoValueID = mysqli_fetch_array( $valueIDQuery)){
							$valueID = $infoValueID['value_id'];
						}
						if(isset($valueID)){
							$value_occurrence_id = GetNewID('value_occurrence');
							mysqli_query("INSERT INTO value_occurrence (value_occurrence_id, value, conjunction)
							VALUES ($value_occurrence_id, $valueID, $conjunctionIDV)") or trigger_error(mysqli_error());
							
							mysqli_query("INSERT INTO value_occurrence_default_choice (value_occurrence, default_choice)
							VALUES ($value_occurrence_id, '$defaultChoice')") or trigger_error(mysqli_error());
						}
					}
					unset ($_SESSION['conjValues']);
				}
				break;
			
			case "form-value-conjunction":
				//adds a new value and its default to choice to the list of values to be added to the DB as a conjunction of values
				if(isset($_SESSION['conjValues']) && $_POST['value']!="N/A"){
					$ConjValue = $_SESSION['conjValues'];
					$value_occurrence = array();
					array_push($value_occurrence, $_POST['value']);
					array_push($value_occurrence, $_POST['default_choice']);
					array_push($ConjValue, $value_occurrence);
					$_SESSION['conjValues'] = $ConjValue;
				}
				break;
				
			case "reset-value-conjunction":
				unset ($_SESSION['conjValues']);
				break;
		default;
	}	
	
	//DELETE CONJUNCTION FROM DATABASE
	if (isset($_POST['DeleteConj'])) {
		DeleteFromTable("conjunction", $_POST['DeleteConj']);
	}
	?>


<?php 
/*Creates the form to display existing propositions conjunctions*/
	$dataConjProp= GetDistinctConjunctions("prop_occurrence");

	Print "<div id='contentWrap'>";
	Print "<div id='contentTop'>";
	Print "<legend><h2>Proposition Conjunctions</h2></legend>";		  
	Print "<table border cellpadding=3>";
	Print "<tr>";
	Print "<th>ID </th><th>Remove</th><th>Propositions</th>";
	
	while($info = mysqli_fetch_array($dataConjProp)){
		$conjID = $info['conjunction_id'];						
		$dataPropositions = mysqli_query("Select proposition_string 
										from proposition, prop_occurrence, conjunction 
										where conjunction_id = prop_occurrence.conjunction 
										and proposition.proposition_id = prop_occurrence.proposition 
										and conjunction_id='$conjID'") or trigger_error(mysqli_error());

		$rowsconjProp =  1+mysqli_num_rows($dataPropositions);
		
		Print "<tr>";
		Print "<td rowspan='$rowsconjProp'>".$conjID. "</td> ";	
		Print "<td rowspan='$rowsconjProp'>";
		print "<form action='conj.php' method='POST'>";
		print "<input type='submit' value='delete'/>";
		print "<input type='hidden' name='DeleteConj' value=".$conjID." />";
		print "</form>";
		print "</td> ";
		while($infoProp = mysqli_fetch_array($dataPropositions)){
			Print "<tr><td>".$infoProp['proposition_string']."</td></tr>";
		}
	}
	Print "</table>";
	Print "</div>";	
	Print	"<div id='contentLeft'>";
	Print	"<ul>";
	Print	"<legend><h2>Propositions</h2></legend>";
	Print	"<fieldset>";
	Print	"<form action='conj.php' method='POST'>";
	print "<p>Porposition: <select name = 'proposition'>";
	echo createStringOptions('proposition', 'proposition_string');
	print "</select></p>";
	print "<input type='hidden' name='mode' value='form-proposition-conjunction'/>";
	print "<input type='submit' value='Add Proposition'>";
	print "</form>";
	print "</fieldset>";
	print "</div>";?>
	
	<?php 
	/*The right hand side
	 * displayes the propositions in the cojunction under construction*/
		print "<div id='contentRight'>";
		print "<ul>";
		if(isset($_SESSION['conjPorporties'])){				
		 foreach ($_SESSION['conjPorporties'] as $prop)
			{
				print "<li>$prop</li>";
			 }
		}
		else{
				global $ConjProps;
				$ConjProps=array();
				$_SESSION['conjPorporties'] = $ConjProps;
		} 
		print "<table>";
		print "<tr>";
		print "<td>";
		print "<form action='conj.php' method='POST'>";
		print "<input type='hidden' name='mode' value='insert-proposition-conjunction'/>";
		print "<input type='submit' value='Submit Propositions'>";
		print "</form>";
		print "</td>";
		print "<td>";
		print "<form action='conj.php' method='POST'>";
		print "<input type='hidden' name='mode' value='reset-proposition-conjunction'/>";
		print "<input type='submit' value='Reset'>";
		print "</form>";
		print "</td>";
		print "</tr>";
		print "</table>";
		print "</ul>";
		print "<p>&nbsp; </p>";
		print "</div>";
		print "</div>";

?>
	
<?php
/*Creates the form to display existing values conjunctions*/
	$dataConjValue = GetDistinctConjunctions("value_occurrence");
	print "<div id='contentWrap'>";
	print "<div id='contentTop'>";
	print "<legend><h2>Values Conjunctions</h2></legend>";	
	Print "<table border cellpadding=3>";
	Print "<tr>";
	Print "<th> ID </th><th>Remove</th><th>Values</th>";
	while($info = mysqli_fetch_array($dataConjValue)){	

		$conjID = $info['conjunction_id'];
		$dataValues = mysqli_query("Select value_name, default_choice
								from value, value_occurrence, conjunction, value_occurrence_default_choice
								where conjunction_id = value_occurrence.conjunction 
                				and value_occurrence_default_choice.value_occurrence = value_occurrence_id
								and value.value_id = value_occurrence.value 
								and conjunction_id=$conjID") or trigger_error(mysqli_error());
		
		$rowsconjValues =  1+mysqli_num_rows($dataValues);
		Print "<tr>";
		Print "<td rowspan='$rowsconjValues'>".$conjID."</td> ";	
		Print "<td rowspan='$rowsconjProp'>";
		print "<form action='conj.php' method='POST'>";
		print "<input type='submit' value='delete'/>";
		print "<input type='hidden' name='DeleteConj' value=".$conjID." />";
		print "</form>";
		print "</td> ";
		
		while($infoValue = mysqli_fetch_array($dataValues)){
			Print "<tr><td>" .$infoValue['value_name']." - ".$infoValue['default_choice']."</td></tr>";
		}
	}
	Print "</table>";
	 Print "</div>";

	 Print "<div id='contentLeft'>";
	Print "<ul>";
	Print "<legend><h2>Values</h2></legend>";
	Print "<fieldset>";
	Print "<form action='conj.php' method='POST'>";
	Print "<p>Values: <select name = 'value'>";
	echo createStringOptions('value', 'value_name'); //value names
	print "</select></p>";
	
	Print "<p>Default Choice: <select name = 'default_choice'>";
	echo createValueOptions(); //default options
	print "</select></p>";
	
	Print "<input type='hidden' name='mode' value='form-value-conjunction' />";
	Print "<input type='submit' value='Add Value'>";
	Print "</form>";
	Print "</fieldset>";

	Print "</div>";
?>
<?php 
/*The right hand side

 * displayes the values in the cojunction under construction*/
	print "<div id='contentRight'>";
	 Print "<ul>";
		if(isset($_SESSION['conjValues'])){				
			foreach ($_SESSION['conjValues'] as $value){
				print "<li>".$value[0]." - ".$value[1]."</li>";
			 }
			}
			else{
					global $ConjValues;
					$ConjValues=array();
					$_SESSION['conjValues'] = $ConjValues;
				} 				
			print "<table>";			
			print "<tr>";
			print "<td>";
			print "<form action='conj.php' method='POST'>";
			print "<input type='hidden' name='mode' value='insert-value-conjunction'/>";
			print "<input type='submit' value='Submit Values'>";
			print "</form>";
			print "</td>";
			print "<td>";
			print "<form action='conj.php' method='POST'>";
			print "<input type='hidden' name='mode' value='reset-value-conjunction'/>";
			print "<input type='submit' value='Reset'>";
			print "</td>";
			print "</tr>";
		  	print "</ul>";
		  	print "<p>&nbsp</p>";
			print "</div>";
	
	print "</div>";
	
print "</body>";
print "</html>";
?>