<?php
/*Displays existing instances of credible soruce scheme
 * allows the user to add new instance from existing intermediates
 
AZW - Nov 12  Do not see what

include ('admin_header.php');

was doing there, so removed it.  Trying to make all the starts of the php to be
consistent.
 */
session_start();
include('../support/database_connect_admin.php');
include('admin_utility.php');
?>

<?php 
/*if the mode is not set --> set to undefined to avoid error message*/
	if (!isset($_POST['mode'])) {
		$_POST['mode'] = "undefine";
	}

/*The actual entry to the database - depends on the forum submitted.
 * Ids are auto generated by the sql (auto incremented fields) */
	switch($_POST['mode']){
	/*insert into
	 * domain_proposition
	 * domain_source
	 * source_proposition - get returned id.
	 * credible_source_as*/
		case "insert_new_csas":
			$domain_source_id = GetNewID("domain_source");	
			InsertIntermediateTableWithID("domain_source", "domain", "source", $_POST['domain'], $_POST['source'], $domain_source_id);

			$domain_proposition_id = GetNewID("domain_proposition");
			InsertIntermediateTableWithID("domain_proposition", "domain", "proposition", $_POST['domain'], $_POST['domainProp'], $domain_proposition_id);			

			$source_proposition_id = GetNewID("source_proposition");	
			InsertIntermediateTableWithID("source_proposition", "source", "proposition", $_POST['source'], $_POST['sourceProp'], $domain_proposition_id);

			/*insert actual instance of the scheme*/
			$sql="INSERT INTO credible_source_as(domain_source, source_proposition, domain_proposition)
			VALUES($domain_source_id,$source_proposition_id,$domain_proposition_id)";
			mysqli_query($sql) or trigger_error(mysqli_error());
			
			break;	
		default;
	}	
	

	if (isset($_POST['DeleteCSAS'])) {
		DeleteFromTable("credible_source_as", $_POST['DeleteCSAS']);
	}

	
?>
<?php
/*GENERATES THE HTML FOR THE PAGE*/
print "<div id='contentWrap'>";
print "<div id='contentTop'>";
print "<legend><h2>Credible Source Scheme Instances</h2></legend>";


/*complex join query to grab all information needed in one go rather than multiple queries*/
	$dataCSAS = mysqli_query("select credible_source_as_id, source_name, domain_name, 
	s.proposition_string as source_porp, 
	d.proposition_string as domain_prop
	from domain, source, credible_source_as, domain_source, domain_proposition, source_proposition, proposition as s, proposition as d
	where credible_source_as.domain_source = domain_source_id
	and credible_source_as.domain_proposition = domain_proposition_id
	and credible_source_as.source_proposition = source_proposition_id
	and domain_source.domain = domain_id
	and domain_source.source = source_id
	and source_proposition.source = source_id
	and domain_proposition.domain = domain_id
	and domain_proposition.proposition = d.proposition_id
	and source_proposition.proposition = s.proposition_id") or trigger_error(mysqli_error()); 

	Print "<table border cellpadding=3 width=80%>";
	Print "<tr>";
	Print "<th>ID</th><th>Source</th><th>Expert in Domain</th><th>Source Proposition</th><th>Domain Proposition</th>";

	while($info = mysqli_fetch_array($dataCSAS)){
		Print "<tr>";
		Print "<td width = 1%>".$info['credible_source_as_id']."</td> ";									
		Print "<td width = 20%>".$info['source_name']."</td> ";
		Print "<td width = 20%>".$info['domain_name']."</td> ";
		Print "<td width = 20%>".$info['source_porp']."</td> ";
		Print "<td width = 20%>".$info['domain_prop']."</td> ";
		Print "<td width = 5%>";
		print "<form action='csas.php' method='POST'>";
		print "<input type='submit' value='delete'/>";
		print "<input type='hidden' name='DeleteCSAS' value=".$info['credible_source_as_id']." />";
		print "</form>";
		print "</td> ";
		print  "</tr>";
	}
	Print "</table>";
?>


<?php
/*creates the insert form*/
print "<p>";
print "<fieldset>";
print "<legend><h2>New Credible Source Scheme</h2></legend>";
print "<form action='csas.php' method='POST'>";
print "<p>Source: <select name = 'source'>";
echo createOptions('source', 'source_id', 'source_name');
print "</select></p>";
print"<p>Expert in Domain: <select name = 'domain'>";
echo createOptions('domain', 'domain_id', 'domain_name');
print "</select></p>";
print "<p>Source Proposition: <select name = 'domainProp'>";
echo createOptions('proposition', 'proposition_id', 'proposition_string');
print "</select></p>";
print "<p>Domain Proposition: <select name = 'sourceProp'>";
echo createOptions('proposition', 'proposition_id', 'proposition_string'); 
print "</select></p>";
print "<input type='hidden' name='mode' value='insert_new_csas'/>";
print "<input type='submit' value='Add'>";
print "</form>";
print "</fieldset>";

print "</body>";
print "</html>";
?>