<?php
/*This PHP attends to the intermediate tables
 * *This PHP attends to the primitive components of the database:
 * 1) domain_source.
 * 2) source_proposition.
 * 3) domain_proposition
*/

/*note that the admin tool allows the user to add and delete relations from the database, but it has no edit function.*/
session_start();
include('../support/database_connect_admin.php');
include('admin_utility.php');

/*this code clears sessions from other admin pages just in case the user was using one before switching to this page.

 * can be commented out if keeping all sessions alive until submission of each page become desirable function -

* comment out from here*/
if(isset($_SESSION['conjPorporties']))
	unset($_SESSION['conjPorporties']);
if(isset($_SESSION['conjValues']))
	unset($_SESSION['conjValues']);
if(isset($_SESSION['conjCSAS']))
	unset($_SESSION['conjCSAS']);
if(isset($_SESSION['conjVRAS']))
	unset($_SESSION['conjVRAS']);
if(isset($_SESSION['newConsultation']))
	unset($_SESSION['newConsultation']);
if(isset($_SESSION['step']))
	unset($_SESSION['step']);
session_unset();
session_destroy();
/*to here*/

?>

<?php 
/*if the mode is not set --> set to undefined to avoid error message*/
if (!isset($_POST['mode'])) {
	$_POST['mode'] = "undefine";
}

/*The actual entry to the database - depends on the forum submitted.
 * Ids are auto generated by the sql (auto incremented fields) */
	switch($_POST['mode']){
		//Domain Source
		case "insert-domain-source":
			if($_POST['domain']!=-1 && $_POST['source']!=-1){	
				InsertIntermediateTable("domain_source", "domain", "source", $_POST['domain'], $_POST['source']);
			}
		break;

		//Source Proposition
		case "insert-source-prop":
			if($_POST['proposition']!=-1 && $_POST['source']!=-1){	
				InsertIntermediateTable("source_proposition", "proposition", "source", $_POST['proposition'], $_POST['source']);
			}
			break;

		//Domain Proposition
		case "insert-domain-prop":
			if($_POST['proposition']!=-1 && $_POST['domain']!=-1){						
				InsertIntermediateTable("domain_proposition", "proposition", "domain", $_POST['proposition'], $_POST['domain']);
			}
			break;
				
		default;
	}	
	

	/*This is the code for deleting relations from the database*/
	if (isset($_POST['DeleteDomainSource'])) {
		DeleteFromTable("domain_source", $_POST['DeleteDomainSource']);
	}
	if (isset($_POST['DeleteDomainProp'])) {
		DeleteFromTable("domain_proposition", $_POST['DeleteDomainProp']);
	}	
	if (isset($_POST['DeleteSourceProp'])) {
		DeleteFromTable("source_proposition", $_POST['DeleteSourceProp']);
	}
?>


<p>
<legend><h2>Domain Source</h2></legend>
<p>
<?php
	CreateDisplayIntermediateTable("domain_source", "Domain", "Source", "domain_source_id", "domain_name", "source_name", "intr.php", "DeleteDomainSource");
?>

<p>
<legend><h2>New Domain Source</h2></legend>
<p>
<fieldset>
<form action="intr.php" method="POST">
<p>Domain: <select name = "domain"><?php  echo createOptions('domain', 'domain_id', 'domain_name') ?></select></p>
<p>Source: <select name = "source"><?php  echo createOptions('source', 'source_id', 'source_name') ?></select></p>
<input type="hidden" name="mode" value="insert-domain-source" />
<input type="submit">
</form>
</fieldset>
<p>


<p>
<legend><h2>Source Proposition </h2></legend>
<p>
<?php
	CreateDisplayIntermediateTable("Source_Proposition", "Proposition", "Source", "source_proposition_id", "proposition_string", "source_name", "intr.php", "DeleteSourceProp");
?>

<p>
<legend><h2>New Source Proposition</h2></legend>
<p>
<fieldset>
<form action="intr.php" method="POST">
<p>Proposition: <select name = "proposition"><?php  echo createOptions('proposition','proposition_id' ,'proposition_string') ?></select></p>
<p>Source: <select name = "source"><?php  echo createOptions('source','source_id', 'source_name') ?></select></p>
<input type="hidden" name="mode" value="insert-source-prop" />
<input type="submit">
</form>
</fieldset>

<p>

<legend><h2>Domain Proposition </h2></legend>
<p>
<?php
	CreateDisplayIntermediateTable("Domain_Proposition", "Proposition", "Domain", "domain_proposition_id", "proposition_string", "domain_name", "intr.php", "DeleteDomainProp");
?>

<p>
<legend><h2>New Domain Proposition</h2></legend>
<p>
<fieldset>
<form action="intr.php" method="POST">
<p>Proposition: <select name = "proposition"><?php  echo createOptions('proposition', 'proposition_id', 'proposition_string') ?></select></p>
<p>Domain: <select name = "domain"><?php  echo createOptions('domain', 'domain_id', 'domain_name') ?></select></p>
<input type="hidden" name="mode" value="insert-domain-prop" />
<input type="submit">
</form>
</fieldset>
<p>




