<?php
/*Displays existing instances of practicial reasoning scheme
 * allows the user to add new instance from existing values and proposition conjunctions as well as existing actions*/
session_start();
include('../support/database_connect_admin.php');
include('admin_utility.php');
?>
<?php 
/*this code clears sessions from other admin pages just in case the user was using one before switching to this page.

 * can be commented out if keeping all sessions alive until submission of each page become desirable function -

* comment out from here*/
if(isset($_SESSION['conjPorporties']))
	unset($_SESSION['conjPorporties']);
if(isset($_SESSION['conjValues']))
	unset($_SESSION['conjValues']);
if(isset($_SESSION['conjCSAS']))

	unset($_SESSION['conjCSAS']);
session_unset();
session_destroy();
/*THIS IS ANOTHER SESSION START IN CASE SESSIONS WERE DESTROYED*/
session_start();
/*to here*/

?>
<?php 
//Global values declerations
/*these globals are arrays used to store the information for the practical reasoning scheme*/
global $consequncesPRAS; 
$consequncesPRAS= array();

global $circumstancesPRAS;
$circumstancesPRAS= array();

global $valuesPRAS;
$valuesPRAS= array();
?>

<?php 
/*if the mode is not set --> set to undefined to avoid error message*/
	if (!isset($_POST['mode'])) {
		$_POST['mode'] = "undefine";
	}

/*The actual entry to the database - depends on the forum submitted.
 * Ids are auto generated by the sql (auto incremented fields) */
	
	switch($_POST['mode']){
		case "insert_new_pras":
			$sql="INSERT INTO practical_reasoning_as (circumstances, action, consequences, practical_reasoning_as.values)
			VALUES($_POST[cicumstances],$_POST[action],$_POST[consequences],$_POST[values])";
			mysqli_query($sql) or trigger_error(mysqli_error());
			break;	
		default;
	}	

	if (isset($_POST['DeletePRAS'])) {
		//DeleteFromTable is defined in the admin_utility.php

		DeleteFromTable("practical_reasoning_as", $_POST['DeletePRAS']);

	}
	

?>


<?php
/*display the list of current Practical Reasoning Scheme Instantiations in the database*/
	print "<legend><h2>Practical Reasoning Scheme Instantiations</h2></legend>";
	$dataPRAS = mysqli_query("SELECT practical_reasoning_as_id, practical_reasoning_as.circumstances, 
			practical_reasoning_as.consequences, practical_reasoning_as.values, action_name, agent_name 
			 from practical_reasoning_as, action, agent 
			where practical_reasoning_as.action = action.action_id and agent.agent_id = action.agent") or trigger_error(mysqli_error()); 

	Print "<table border cellpadding=3 width=80%>";
	Print "<tr>";
	Print "<th>ID</th><th>Circumstances</th><th>Action</th><th>Agent</th><th>Consequences</th><th>Values</th><th>Remove</th>";
	
		
	while($info = mysqli_fetch_array($dataPRAS)){
		$valuesString = GetPRASComponentInfoString("value", "value_name", "value_occurrence", $info['values']);

		$conseqString = GetPRASComponentInfoString("proposition", "proposition_string", "prop_occurrence", $info['consequences']);

		$circumString = GetPRASComponentInfoString("proposition", "proposition_string", "prop_occurrence", $info['circumstances']);
		
		Print "<tr>";
		Print "<td width = 1%>".$info['practical_reasoning_as_id']."</td> ";									
		Print "<td width = 20%>".$circumString."</td> ";
		Print "<td width = 10%>".$info['action_name']."</td> ";
		Print "<td width = 4%>".$info['agent_name']."</td> ";
		Print "<td width = 20%>".$conseqString."</td> ";
		Print "<td width = 20%>".$valuesString."</td> ";

		Print "<td>";

		print "<form action='pras.php' method='POST'>";

		print "<input type='submit' value='delete'/>";

		print "<input type='hidden' name='DeletePRAS' value=".$info['practical_reasoning_as_id']." />";

		print "</form> ";

		print "</td> ";
		print  "</tr>";
	}
	Print "</table>";
?>


<?php
/*Generates the information for the drop down menues in the form*/
	$conjunction = mysqli_query("select distinct conjunction_id from conjunction") or trigger_error(mysqli_error());
	while($infoConj = mysqli_fetch_array($conjunction)){
		//get conjunction id
		$conjID = $infoConj['conjunction_id'];
		$valueString = GetPRASComponentInfoString("value", "value_name", "value_occurrence", $conjID);

		$propString = GetPRASComponentInfoString("proposition", "proposition_string", "prop_occurrence", $conjID);


		//add to array
		$propArray = array();
		if($propString!=""){

			array_push($propArray, $conjID);

			array_push($propArray, $propString);

			array_push($consequncesPRAS, $propArray);

			array_push($circumstancesPRAS, $propArray);
			

		}

		//add to array
		if($valueString!=""){
			$val = array();

			array_push($val, $conjID);

			array_push($val, $valueString);

			array_push($valuesPRAS, $val);
		}
	}
?>

<p>
<fieldset>
<legend><h2>New Practical Reasoning Scheme Instance</h2></legend>
<form action="pras.php" method="POST">
<p>Cicumstances: <select name = "cicumstances"><?php  echo createOptionsArray($circumstancesPRAS) ?></select></p>
<p>
<p>Action: <select name = "action"><?php  echo createOptions("action", 'action_id', 'action_name') ?></select></p>
<p>
<p>Consequences: <select name = "consequences"><?php  echo createOptionsArray($consequncesPRAS) ?></select></p>
<p>
<p>Value: <select name = "values"><?php  echo createOptionsArray($valuesPRAS) ?></select></p>
<input type="hidden" name="mode" value="insert_new_pras" />
<input type="submit" value="Add">
</form>
</fieldset>
<p>