<?php
/*This PHP attends to the primitive components of the database:
 * 1) Propositions.
 * 2) Values.
 * 3) Agents
 * 4) Actions
 * 5) Domain
 * 6) Source*/

/*note that the admin tool allows the user to add and delete relations from the database, but it has no edit function.
AZW - Nov 12.  Removed

include('admin_header.php');

Does not seem to add much to the style on this page.

Have also removed them from all following pages as not clear to me that 
it makes a difference there and the code behaves differently on different
pages.
*/
session_start();
include('../support/database_connect_admin.php');
include('admin_utility.php');


/*this code clears sessions from other admin pages just in case the user was using one before switching to this page. 
 * can be commented out if keeping all sessions alive until submission of each page become desirable function -
 * comment out from here*/
if(isset($_SESSION['conjPorporties']))
	unset($_SESSION['conjPorporties']);
if(isset($_SESSION['conjValues']))
	unset($_SESSION['conjValues']);
if(isset($_SESSION['conjCSAS']))
	unset($_SESSION['conjCSAS']);
if(isset($_SESSION['conjVRAS']))
	unset($_SESSION['conjVRAS']);
if(isset($_SESSION['newConsultation']))
	unset($_SESSION['newConsultation']);
if(isset($_SESSION['step']))
	unset($_SESSION['step']);
session_unset();
session_destroy();
/*to here*/
?>

<?php 
/*if the mode is not set --> set to undefined to avoid error message*/
if (!isset($_POST['mode'])) {
	$_POST['mode'] = "undefine";
}

/*The actual entry to the database - depends on the forum submitted.
 * Ids are auto generated by the sql (auto incremented fields) */
switch($_POST['mode']){
		/*Agents*/
		case "insert-agent":
			//InsertPrimitveTable is defined in the admin_utility.php
			InsertPrimitveTable("Agent", "agent_name", $_POST['agent_name']);
		break;
		/*Actions
		 * Actions are different to other primitives because they have two values: name and agent id*/
		case "insert-action":
			if($_POST['agent']!=-1){
				$sql="INSERT INTO action (action_name, agent)
				VALUES ('$_POST[action_name]',$_POST[agent])";
				mysqli_query($sql) or trigger_error(mysqli_error());
			}
			break;
		/*Propositions*/
		case "insert-proposition":
			InsertPrimitveTable("proposition", "proposition_string", $_POST['proposition_string']);
		break;
		/*Values*/
		case "insert-value":
			InsertPrimitveTable("value", "value_name", $_POST['value_name']);
		break;
		/*Domains*/
		case "insert-domain":
			InsertPrimitveTable("domain", "domain_name", $_POST['domain_name']);
		break;
		/*Sources*/
		case "insert-source":
			InsertPrimitveTable("source", "source_name", $_POST['source_name']);
		break;
		default;
	}	
	
	/*This is the code for deleting relations from the database*/
	if (isset($_POST['DeleteAction'])) {
		//DeleteFromTable is defined in the admin_utility.php
		DeleteFromTable("Action", $_POST['DeleteAction']);
	}	
	if (isset($_POST['DeleteAgent'])) {
		DeleteFromTable("Agent", $_POST['DeleteAgent']);
	}	
	if (isset($_POST['DeleteProposition'])) {
		DeleteFromTable("Proposition", $_POST['DeleteProposition']);
	}	
	if (isset($_POST['DeleteValue'])) {
		DeleteFromTable("Value", $_POST['DeleteValue']);
	}	
	if (isset($_POST['DeleteDomain'])) {
		DeleteFromTable("Domain", $_POST['DeleteDomain']);
	}
	if (isset($_POST['DeleteSource'])) {
		DeleteFromTable("Source", $_POST['DeleteSource']);
	}
	

?>
<legend><h2>Agents</h2></legend>
<p>
<?php
/*defined in admin_utility.php*/
CreateDisplayTableTwoFields("Agent", "agent_id", "agent_name", "prim.php", "DeleteAgent");
?>
<fieldset>
<form action="prim.php" method="POST">
<p>Agent: <input type="text" name="agent_name" /></p>
<input type="hidden" name="mode" value="insert-agent" />
<input type="submit">
</form>
</fieldset>

<legend><h2>Actions</h2></legend>
<?php
	/*because actions have three displayed values: id, name and agent name I left it as separated query. 
	 *Maya */
	$dataAction = mysqli_query("SELECT action_id, action_name, agent_name FROM action, agent where action.agent = agent.agent_id") or trigger_error(mysqli_error()); 	
	Print "<table border cellpadding=3>";
	Print "<tr>";
	Print "<th>ID</th><th>Action</th><th>Agent</th><th>Remove</th>";
	while($info = mysqli_fetch_array( $dataAction )){ 
		Print "<tr>";
		Print "<td>".$info['action_id']. "</td> ";
		Print "<td>".$info['action_name'] . "</td> ";
		Print "<td>".$info['agent_name'] . "</td> ";
		Print "<td>";
		print "<form action='prim.php' method='POST'>";
		print "<input type='submit' value='delete'/>";
		print "<input type='hidden' name='DeleteAction' value=".$info['action_id']." />";
		print "</form> ";
		print "</td> ";
	} 
	Print "</table>"; 
	
	$agentInfo = mysqli_query("SELECT agent_id, agent_name FROM agent") or trigger_error(mysqli_error());
?>

<p>

<fieldset>
<form action="prim.php" method="POST">
<p>Action: <input type="text" name="action_name" /></p>
<p>Agent: <select name = "agent"><?php  echo createOptions('agent', 'agent_id', 'agent_name') ?></select></p>
<input type="hidden" name="mode" value="insert-action" />
<input type="submit">
</form>
</fieldset>
<p>


<legend><h2>Values</h2></legend>
<p>
<?php
	CreateDisplayTableTwoFields("Value", "value_id", "value_name", "prim.php", "DeleteValue");
?>
<fieldset>
<form action="prim.php" method="POST">
<p>Value: <input type="text" name="value_name" /></p>
<input type="hidden" name="mode" value="insert-value" />
<input type="submit">
</form>
</fieldset>

<p>
<legend><h2>Propositions</h2></legend>
<?php
CreateDisplayTableTwoFields("Proposition", "proposition_id", "proposition_string", "prim.php", "DeleteProposition");
?>
<p>
<fieldset>
<form action="prim.php" method="POST">
<p>Proposition: <input type="text" name="proposition_string" /></p>
<input type="hidden" name="mode" value="insert-proposition" />
<input type="submit">
</form>
</fieldset>
<p>

<legend><h2>Domains</h2></legend>
<?php
	CreateDisplayTableTwoFields("Domain", "domain_id", "domain_name", "prim.php", "DeleteDomain");
?>
<p>
<fieldset>
<form action="prim.php" method="POST">
<p>Domain Name: <input type="text" name="domain_name" /></p>
<input type="hidden" name="mode" value="insert-domain" />
<input type="submit">
</form>
</fieldset>
<p>
<legend><h2>Sources</h2></legend>
<?php
	CreateDisplayTableTwoFields("Source", "source_id", "source_name", "prim.php", "DeleteSource");
?>
<p>
<fieldset>
<form action="prim.php" method="POST">
<p>Source Name: <input type="text" name="source_name" /></p>
<input type="hidden" name="mode" value="insert-source" />
<input type="submit">
</form>
</fieldset>
