<?php
/*Displays existing instances of value credible soruce scheme

 * allows the user to add new instance from existing intermediates*/
session_start();
include('../support/database_connect_admin.php');
include('admin_utility.php');

//returns real ID if the source is alread in DB or generates new ID if not.
function GenerateDomainSourceID($domain, $source){ 
	$domainData = mysqli_query("Select domain_source_id from domain_source where domain = $domain and source=$source") or trigger_error(mysqli_error());
	if(mysqli_num_rows($domainData)>0){
		$infoDomain = mysqli_fetch_array($domainData);
		$domainID = $infoDomain['domain_source_id'];
		return $domainID;
	}

	else{
		$domainID = GetNewID("domain_source");
		InsertIntermediateTableWithID("domain_source", "domain", "source", $domain, $source, $id);
		return $domainID;
	}
}

//inserts new instance of Value Credible Source to DB if similar instance doesn't exist
function InsertNewValueCredibleSource($domain_source, $action, $value_default_choice){ //return real ID if the source is alread in DB or generates new ID if not.
	$data = mysqli_query("Select value_credible_source_as_id
			from value_credible_source_as
			where domain_source = $domain_source
			and action=$action
			and value_occurrence_default_choice=$value_default_choice") or trigger_error(mysqli_error());
	if(mysqli_num_rows($data)>0){
		return;
	}
	else{
		mysqli_query("INSERT INTO value_credible_source_as (domain_source, action, value_occurrence_default_choice)
		VALUES ($domain_source, $action, $value_default_choice)") or trigger_error(mysqli_error());
	}
}


?>

<?php 
/*if the mode is not set --> set to undefined to avoid error message*/
if (!isset($_POST['mode'])) {
	$_POST['mode'] = "undefine";
}

/*The actual entry to the database - depends on the forum submitted.
 * Ids are auto generated by the sql (auto incremented fields) */

	switch($_POST['mode']){
		case "insert_new_vcsas":
			$domain_source_id = GenerateDomainSourceID($_POST['domain'], $_POST['source']);
			InsertNewValueCredibleSource($domain_source_id, $_POST['action'], $_POST['value_choice']);	
			break;				
		default;
	}	
	
	//delete from DB
	if (isset($_POST['DeleteVSAS'])) {
		DeleteFromTable("value_credible_source_as", $_POST['DeleteVSAS']);
	}
	
?>
<?php
/*generates HTML code to display existing instances in the DB*/
print "<div id='contentWrap'>";
print "<div id='contentTop'>";
print "<legend><h2>Credible Source Schemes</h2></legend>";

//complex query to get all scheme infromation in one go rather than multiple queries
	$dataVCSAS = mysqli_query("select value_credible_source_as_id, source_name, domain_name, 
							value_name,value_occurrence_default_choice.default_choice, action_name
							from value_credible_source_as, 
							     domain_source, domain, source,
							     action, 
							     value_occurrence_default_choice, value_occurrence, value
							where value_credible_source_as.domain_source=domain_source_id
							and value_credible_source_as.action = action_id
							and domain_source.source = source_id
							and domain_source.domain=domain_id
							and value_credible_source_as.value_occurrence_default_choice = value_occurrence_default_choice_id
							and value_occurrence_default_choice.value_occurrence = value_occurrence_id
							and value_occurrence.value = value_id") or trigger_error(mysqli_error()); 

	Print "<table border cellpadding=3 width=80%>";
	Print "<tr>";
	Print "<th>ID</th><th>Source</th><th>Expert in Domain</th><th>Value</th><th>Default Choice</th><th>Action</th>";
	
		
	while($info = mysqli_fetch_array($dataVCSAS)){
		Print "<tr>";
		Print "<td width = 1%>".$info['value_credible_source_as_id']."</td> ";									
		Print "<td width = 20%>".$info['source_name']."</td> ";
		Print "<td width = 20%>".$info['domain_name']."</td> ";
		Print "<td width = 20%>".$info['value_name']."</td> ";
		Print "<td width = 20%>".$info['default_choice']."</td> ";
		Print "<td width = 20%>".$info['action_name']."</td> ";
		Print "<td width = 5%>";

		print "<form action='csas.php' method='POST'>";
		print "<input type='submit' value='delete'/>";
		print "<input type='hidden' name='DeleteVSAS' value=".$info['value_credible_source_as_id']." />";
		print "</form>";
		print "</td> ";
		print  "</tr>";
	}
	Print "</table>";
?>


<?php
/*generates HTML code for the insert form*/
$valueData = mysqli_query("select value_occurrence_default_choice_id, Concat(value_name, ' - ' , default_choice) as value_choice
from value_occurrence_default_choice, value_occurrence, value
where value_occurrence_default_choice.value_occurrence = value_occurrence_id
and value_occurrence.value = value_id") or trigger_error(mysqli_error());

print "<p>";
print "<fieldset>";
print "<legend><h2>New Value Credible Source Scheme Instance</h2></legend>";
print "<form action='vcsas.php' method='POST'>";
print "<p>Source: <select name = 'source'>";
echo createOptions('source', 'source_id', 'source_name');
print "</select></p>";
print"<p>Expert in Domain: <select name = 'domain'>";
echo createOptions('domain', 'domain_id', 'domain_name');
print "</select></p>";
print "<p>Says that Action: <select name = 'action'>";
echo createOptions('action', 'action_id', 'action_name');
print "</select></p>";
print "<p>Relates to Value: <select name = 'value_choice'>";
echo createOptionsFromDataSet($valueData, 'value_occurrence_default_choice_id', 'value_choice'); 
print "</select></p>";
print "<input type='hidden' name='mode' value='insert_new_vcsas'/>";
print "<input type='submit' value='Add'>";
print "</form>";
print "</fieldset>";

print "</body>";
print "</html>";
?>